import re

def extract_pr_numbers(text):
    pr_nums = set()
    pr_nums.update(re.findall(r'#(\d+)', text))
    pr_nums.update(re.findall(r'pull/(\d+)', text))
    pr_nums = sorted(int(n) for n in pr_nums)
    return pr_nums

if __name__ == "__main__":
    # 把pr_link的文本放在pr_text变量中
    pr_text = """
feat(ai-proxy): support Amazon Bedrock Image Generation by @daixijun in #2212
fix: Fix the incorrect rewrite config generated for Nacos 3 MCP Servers by @CH3CHO in #2211
feat: update translate-readme action by @littlejiancc in #2208
fix: Remove the Authorization request header when using AI-proxy to proxy Gemini by @hanxiantao in #2220
fix : fix issue #2222 by @Erica177 in #2231
Add test translation workflow by @MAVRICK-1 in #2228
mcp server support API auth through OAS3 security schemes by @johnlanni in #2241
Fix : add fail strategy for wasmplugin generated by mcp server by @Erica177 in #2237
fix: modify log level WARN -> DEBUG in key-auth plugin by @lexburner in #2275
fix proxy-wasm-cpp-sdk by @johnlanni in #2281
feat: Supports recording request header, request body, response header and response body information in the access log by @forgottener in #2265
feat(mcp-server): add HackMD mcp server by @Whitea029 in #2260
add mcp service shebao tools by @hourmoneys in #2303
feat: Add a github action to copy CRD definitions from api folder to helm folder by @CH3CHO in #2268
feat: allow skipping higress dev image build during wasmplugin e2e tests by @cr7258 in #2264
feat: Refactor mcpServer.matchList config generation logic by @CH3CHO in #2207
add info log of ai-search plugin by @johnlanni in #2323
fix(ai-proxy): URL encode model name in Bedrock requests by @HecarimV in #2321
feat(ai-proxy): add doubao Image Generation support by @daixijun in #2331
feat: cluster-key-rate-limit support setting global rate limit thresholds for routes​ by @hanxiantao in #2262
feat(ai-proxy): support OpenAI-compatible image and audio model Mapping by @daixijun in #2341
fix: set "EnableSemanticCachefalse" to false when no vector configured in ai-cache by @mirror58229 in #2351
feat(ai-proxy): add batches & files support by @daixijun in #2355
feat: support dify ai-proxy e2e test || feat: support diify ai-proxy e2e test by @VinciWu557 in #2319
fix content-length header not remove in ai-search plugin by @johnlanni in #2363
feat(ai-proxy): add modelMapping regexp support by @daixijun in #2358
feat(ai-proxy): Fixed the issue that the API pass-through path error does not support openaiCustomUrl after openai is configured. by @daixijun in #2364
feat(frontend-gray): Add uniqueGrayTag configuration detection by @heimanba in #2371
feat(ai-proxy): add models & image generation support for gemini by @daixijun in #2380
feat(ai-proxy): support Google Cloud Vertex by @HecarimV in #2119
add upstream override wasm abi by @johnlanni in #2387
feat(ai-proxy): Add Claude image understanding and Tools calling capabilities by @daixijun in #2385
fix: refactored mcp server auto discovery logic and fix some issue by @Erica177 in #2382
fix : fix credential process logic for nacos mcp util and add ut for it by @Erica177 in #2394
fix: Support mixing line breaks in a single SSE response by @CH3CHO in #2344
Update CRD file in the helm folder by @github-actions in #2392
    """
    pr_num_list = extract_pr_numbers(pr_text)
    print(','.join(str(n) for n in pr_num_list))